#!/usr/bin/env bash
# does not affect header in process by redirecting header to stderr
#
# example: { cat /tmp/test.csv | csvskiphead | sed 's/^/$$$$$/g' ; } &> /tmp/out
cat - | head -n1 1>&2
cat - | tail -n+2 
